// export { default as AdminDashboardSkeleton } from "./AdminDashboardSkeleton";
export * from "./AdminDashboardSkeleton";
export { default as AdminOrderDetailsSkeleton } from "./AdminOrderDetailsSkeleton";
export { default as AdminOrdersListSkeleton } from "./AdminOrdersListSkeleton";
export { default as AdminProductDetailsSkeleton } from "./AdminProductDetailsSkeleton";
export { default as AdminProductsListSkeleton } from "./AdminProductsListSkeleton";
export { default as CartSkeleton } from "./CartSkeleton";
export { default as MyOrdersSkeleton } from "./MyOrdersSkeleton";
export { default as ProductCardSkeleton } from "./ProductCardSkeleton ";
export { default as ProductDetailsSkeleton } from "./ProductDetailsSkeleton";
export { default as TrackOrderSkeleton } from "./TrackOrderSkeleton";