# Generated by Django 6.0.1 on 2026-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pattern',
            field=models.CharField(choices=[('printed', 'Printed'), ('solid', 'Solid'), ('checks', 'Checks'), ('stripes', 'stripes'), ('vintage', 'Vintage'), ('textured', 'Self-Design / Textured'), ('embroidered', 'Embroidered')], max_length=20),
        ),
    ]
