# Generated by Django 6.0.1 on 2026-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0007_remove_product_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='hex_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
