# Generated by Django 6.0.1 on 2026-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0008_productimage_color_name_productimage_hex_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
