# Generated by Django 6.0.1 on 2026-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0009_alter_wholesaler_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='pan',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
