# Generated by Django 6.0.1 on 2026-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0010_wholesaler_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
