# Generated by Django 6.0.1 on 2026-02-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0012_color_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='hex_code',
        ),
    ]
