# Generated by Django 6.0.1 on 2026-02-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0013_remove_productimage_color_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
