# Generated by Django 6.0.1 on 2026-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0014_delete_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
