# Generated by Django 6.0.1 on 2026-03-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0015_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(blank=True, choices=[('vintage', 'Vintage'), ('retro', 'Retro'), ('modern', 'Modern'), ('streetwear', 'Streetwear')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, choices=[('printed', 'Printed'), ('solid', 'Solid'), ('checks', 'Checks'), ('stripes', 'stripes'), ('textured', 'Self-Design / Textured'), ('embroidered', 'Embroidered')], max_length=20, null=True),
        ),
    ]
