# Generated by Django 6.0.1 on 2026-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0016_product_style_alter_product_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-Shirts'), ('linen', 'Linen Shirts'), ('silk', 'silk Shirts'), ('denim', 'Denim Shirts'), ('casual', 'Casual Shirts'), ('formal', 'Formal Shirts')], max_length=50),
        ),
    ]
