# Generated by Django 6.0.1 on 2026-07-24 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0017_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wholesaler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='banana_core.wholesaler')),
            ],
        ),
    ]
