# Generated by Django 6.0.1 on 2026-07-24 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0018_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='banana_core.cart')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banana_core.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banana_core.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banana_core.size')),
            ],
        ),
    ]
