# Generated by Django 6.0.1 on 2026-08-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0021_remove_order_user_order_wholesaler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
