# Generated by Django 6.0.1 on 2026-08-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0022_alter_wholesaler_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
