# Generated by Django 6.0.1 on 2026-08-05 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0023_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_pincode',
            field=models.CharField(default=1, max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
