# Generated by Django 6.0.1 on 2026-08-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0024_order_shipping_city_order_shipping_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
