# Generated by Django 6.0.1 on 2026-08-06 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0025_order_cancelled_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.datetime(2026, 8, 6, 15, 10, 29, 804517, tzinfo=datetime.timezone.utc)),
        ),
    ]
