# Generated by Django 6.0.1 on 2026-08-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0027_alter_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('tshirt', 'T-Shirts'), ('linen', 'Linen Shirts'), ('silk', 'Silk Shirts'), ('denim', 'Denim Shirts'), ('casual', 'Casual Shirts'), ('formal', 'Formal Shirts')], max_length=50),
        ),
    ]
