# Generated by Django 6.0.1 on 2026-08-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0028_order_order_number_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
