# Generated by Django 6.0.1 on 2026-08-15 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0029_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaler',
            name='billing_city',
            field=models.CharField(default='Temp City', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='billing_pincode',
            field=models.CharField(default='000000', max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='billing_state',
            field=models.CharField(default='Temp state', help_text='State tied to your GSTIN registration', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='billing_street',
            field=models.TextField(default='Temp street', help_text='Shop/Plot No., Building, Street Name'),
            preserve_default=False,
        ),
    ]
