# Generated by Django 6.0.1 on 2026-08-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0030_wholesaler_billing_city_wholesaler_billing_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
