# Generated by Django 6.0.1 on 2026-08-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0032_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
