# Generated by Django 6.0.1 on 2026-09-02 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0033_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='billing_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='billing_pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='PIN code must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='billing_state',
            field=models.CharField(blank=True, help_text='State tied to your GSTIN registration', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='billing_street',
            field=models.TextField(blank=True, help_text='Shop/Plot No., Building, Street Name', null=True),
        ),
        migrations.AlterField(
            model_name='wholesaler',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
