# Generated by Django 6.0.1 on 2026-09-13 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana_core', '0034_alter_wholesaler_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaler',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
